### ISSUE TITLE
No jar file!

### ISSUE THREAD

**Issue by damithc** [chensu2436/duke#9]
@chensu2436 you don't have a jar file for your iP. Without a jar file, we are unable to give you a score for the iP.

Please release a jar file that is cross-platform and confirmed to work with Java 11. When it is ready, post here to let me know ASAP (deadline: a week from today).

**Comment by chensu2436** [comment]
I have released a jar file 19 days ago in my Release and the release name is Duke iP Product, but it's on the second page of the Release so need to click Next to view it (I'm not sure why this happened to be not on the first page).

**Comment by damithc** [comment]
Found it. It doesn't appear in the first page of your releases https://github.com/chensu2436/duke/releases because you have pushed many tags after that.
